// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDtROla1WEa5BqQaDK6tife_Nj0UcrS0c',
    appId: '1:1054031118120:web:d0cd3e7145cd644b05da1d',
    messagingSenderId: '1054031118120',
    projectId: 'zeus-83b7e',
    authDomain: 'zeus-83b7e.firebaseapp.com',
    storageBucket: 'zeus-83b7e.firebasestorage.app',
    measurementId: 'G-5ZFGZM25F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2aI4b5m4fqi5UL4ZeVu1IwsRVF_SH_Io',
    appId: '1:1054031118120:android:58a2df4bde23789505da1d',
    messagingSenderId: '1054031118120',
    projectId: 'zeus-83b7e',
    storageBucket: 'zeus-83b7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUsmSpYLmbf8n73-HRNEfjDsf5ISUFtd4',
    appId: '1:1054031118120:ios:6efa7027cfc6982105da1d',
    messagingSenderId: '1054031118120',
    projectId: 'zeus-83b7e',
    storageBucket: 'zeus-83b7e.firebasestorage.app',
    iosBundleId: 'com.example.zeus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUsmSpYLmbf8n73-HRNEfjDsf5ISUFtd4',
    appId: '1:1054031118120:ios:6efa7027cfc6982105da1d',
    messagingSenderId: '1054031118120',
    projectId: 'zeus-83b7e',
    storageBucket: 'zeus-83b7e.firebasestorage.app',
    iosBundleId: 'com.example.zeus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDtROla1WEa5BqQaDK6tife_Nj0UcrS0c',
    appId: '1:1054031118120:web:efda0e706e7bb5ac05da1d',
    messagingSenderId: '1054031118120',
    projectId: 'zeus-83b7e',
    authDomain: 'zeus-83b7e.firebaseapp.com',
    storageBucket: 'zeus-83b7e.firebasestorage.app',
    measurementId: 'G-H2BBHFFR2Y',
  );
}
